# Generated by Django 5.2.15 on 2026-06-05 04:39

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("extras", "0142_remove_scheduledjob_approval_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("key", models.SlugField(max_length=255, unique=True)),
                ("category", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("formula", models.TextField(blank=True)),
                ("baseline_value", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("target_value", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Metric Definition",
                "verbose_name_plural": "Metric Definitions",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="MetricValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=18)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                (
                    "metric_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="lipford_nautobot_metrics.metricdefinition",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Metric Value",
                "verbose_name_plural": "Metric Values",
                "ordering": ["-recorded_at", "metric_definition__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("metric_definition", "recorded_at", "source"),
                        name="lipford_metrics_unique_definition_recorded_source",
                    )
                ],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
    ]
